### ISSUE TITLE
0.17.0 release — TODOs before the release

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1376]
### Description

- [x] add docs for ARRAY type input - include screenshots of how it's represented in the UI + show benefit of validation of itemType e.g. execution fails to be created on wrong types
- [x] How-To guide for SyncFlows in the same way as https://kestra.io/docs/how-to-guides/pushflows 
- [x] How-To guide for SyncNamespaceFiles in the same way as https://kestra.io/docs/how-to-guides/pushflows 
- [x] How-To guide for PushNamespaceFiles in the same way as https://kestra.io/docs/how-to-guides/pushflows 
- [x] How-To guide for Pause with inputs incl. screenshots of the UI and Slack - can be added as a new section to https://kestra.io/docs/how-to-guides/pause-resume e.g. "Providing custom inputs to the Pause/Resume pattern"
- [x] add a PR renaming all plugins to the new naming schema e.g. Schedule is now part of Core Plugin, so all Schedule trigger mentions need to be adjusted etc. -- might be best to do the change on the develop docs branch https://github.com/kestra-io/docs/issues/1370
- [x] ensure this is merged https://github.com/kestra-io/docs/issues/1375 

---

Notes for ARRAY

 `ARRAY` input type allows you to specify the type of the array elements using the `itemType` property.

[This feature](https://github.com/kestra-io/kestra/issues/771) is particularly useful when you want the end user triggering the workflow to provide multiple values of a specific type, e.g. a list of integers, strings, booleans, or datetimes. You can provide the default values as a JSON array or as a YAML list.

```yaml
id: array_demo
namespace: dev

inputs:
  - id: my_numbers
    type: ARRAY
    itemType: INT
    defaults: [1, 2, 3, 4, 5]

  - id: my_numbers2
    type: ARRAY
    itemType: INT
    defaults: 
      - 1
      - 2
      - 3
      - 4
      - 5

  - id: my_strings
    type: ARRAY
    itemType: STRING
    defaults: ["my", "pretty", "inputs"]

  - id: my_strings2
    type: ARRAY
    itemType: STRING
    defaults: 
      - my
      - pretty
      - inputs

  - id: my_booleans
    type: ARRAY
    itemType: BOOLEAN
    defaults: [true, true, false]

  - id: my_booleans2
    type: ARRAY
    itemType: BOOLEAN
    defaults: 
      - true
      - true
      - false

  - id: my_datetimes
    type: ARRAY
    itemType: DATETIME
    defaults: ["2024-08-09T14:19:00Z", "2024-08-09T15:19:00Z"]
    
  - id: my_datetimes2
    type: ARRAY
    itemType: DATETIME
    defaults:
      - "2024-08-09T14:19:00Z"
      - "2024-08-09T15:19:00Z"

tasks:
  - id: print_status
    type: io.kestra.plugin.core.log.Log
    message: received inputs {{ inputs }}
```
