### ISSUE TITLE
Improve Debezium documentation (how to guide explaining how the plugin works with Realtime Triggers and batch/polling triggers)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1434]
### Description

Debezium triggers require a lot of setup.

Often, users expect that they can just point the plugin to their desired DB, and CDC will work out of the box to trigger the flow anytime there is a new row in the DB, like so:

```yaml
id: hello-world
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - cat "{{trigger.uris}}"

triggers:
  - id: listen-debezium
    type: io.kestra.plugin.debezium.postgres.Trigger
    hostname: host.docker.internal
    port: "5432"
    username: postgres
    password: "kestra"
    database: taxi
    pluginName: PGOUTPUT
    snapshotMode: INITIAL
    format: INLINE
    interval: PT3S
```

We should make it clear in the documentation:
- any prerequisites on the Debezium configuration side
- using the Realtime Trigger to capture each row/change separately
- using the batch/polling trigger to capture multiple rows that changed within a given interval
- explain the difference in how changed data is captured by the plugin e.g. URI of an internal storage file for the polling trigger and raw data for the realtime trigger
