### ISSUE TITLE
Add full plugin examples to all Serialization Tasks

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1443]
### Description

The Examples can download some files from https://huggingface.co/datasets/kestra/datasets/tree/main and convert them to the desired format - example flow showing how we can download some files and use conversion tasks to get the data into the right format (no need to use DuckDB everywhere, just an example here).

```yaml
id: duckdb_query
namespace: blueprint

tasks:
  - id: download_csv
    type: io.kestra.plugin.fs.http.Download
    description: salaries of data professionals from 2020 to 2023 (source ai-jobs.net)
    uri: https://huggingface.co/datasets/kestra/datasets/raw/main/csv/salaries.csv

  - id: avg_salary_by_job_title
    type: io.kestra.plugin.jdbc.duckdb.Query
    inputFiles:
      data.csv: "{{ outputs.download_csv.uri }}"
    sql: |
      SELECT 
        job_title,
        ROUND(AVG(salary),2) AS avg_salary
      FROM read_csv_auto('{{ workingDir }}/data.csv', header=True)
      GROUP BY job_title
      HAVING COUNT(job_title) > 10
      ORDER BY avg_salary DESC;
    store: true

  - id: result
    type: io.kestra.plugin.serdes.csv.IonToCsv
    from: "{{ outputs.avg_salary_by_job_title.uri }}"
```

The goal is that all `IonToXYZ` and `XYZToIon` tasks have full examples within the plugin documentation so that it's displayed in the documentation how to use them. 

- [ ] CsvToIon
- [ ] IonToCsv
- [ ] JsonToIon
- [ ]  IonToJson
- [ ] AvroToIon
- [ ] IonToAvro
- [ ] XmlToIon
- [ ] IonToXml
- [ ] ParquetToIon
- [ ] IonToParquet
