### ISSUE TITLE
​Execution​Status​Condition for transient states

### ISSUE THREAD

**Issue by rtl-perse** [kestra-io/docs#1543]
### Issue description

My goal was to use a Flow trigger with `ExecutionFlowCondition` to get notified via Teams/Slack for `PAUSED` human in the loop executions.

From my investigation, the `ExecutionFlowCondition` does currently only work with terminal states.
Can you add support for transient states such as `PAUSED` or `QUEUED`?
Or if this is not possible, please add this information the documentation.

Example Execution Flow:
```yaml
id: do_pause
namespace: company.myteam

tasks:
  - id: take_a_break
    type: io.kestra.plugin.core.flow.Pause
    timeout: PT1M

concurrency:
  limit: 1
```

Trigger Flow (never triggered):
```yaml
id: trigger_by_pause
namespace: company.myteam

tasks:
  - id: log_trigger_state
    type: io.kestra.plugin.core.log.Log
    message: "state: {{ trigger.state }}"

triggers:
  - id: test_trigger
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionFlowCondition
        namespace: company.myteam
        flowId: do_pause
      - type: io.kestra.plugin.core.condition.ExecutionStatusCondition
        in:
          - QUEUED
          - PAUSED
```

- Kestra Version: 0.17.9
- Operating System (OS/Docker/Kubernetes): Kubernetes
- Java Version (if you don't run kestra in Docker):
