### ISSUE TITLE
Add frontmatter fields allowing to mark some documentation pages as deprecated since a given release along with migration guide URL

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1605]
### Description

Similarly to how we can add Edition and Version markers, it would be cool to allow marking some features as deprecated in the docs. 

```
---
title: My page
icon: /docs/icons/admin.svg
editions: ["EE"]
version: ">= 0.10.0"
deprecated:
  since: "0.18.0"
  migrationGuide: /docs/migration-guide/0.17.0/local-files
---
```
![image](https://github.com/user-attachments/assets/28ba867b-d7ec-4fc2-b886-dee5f11e0798)

Note that worker groups are not deprecated! This is just an example to show what is meant.
