### ISSUE TITLE
[Post-Release action] Add Breaking Changes for 0.18.0 to GitHub Release Notes

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1609]
### Docker image tags

We've [changed](https://github.com/kestra-io/kestra/issues/4275) our **Docker image tags** to ensure that the **default** `kestra/kestra:latest` image is the one with **all plugins**. Most of our users leverage Kestra version with all plugins included, so we want to make sure that the default Docker image is the one that includes all plugins. To use a lightweight version of Kestra without plugins, you will now have to explicitly use the suffix `*-no-plugins`.

Before upgrading to Kestra 0.18.0, make sure to adjust the image in your deployment as follows:
- `kestra/kestra:latest` if you want to always use the latest stable version of Kestra and have all plugins included in the image
- `kestra/kestra:latest-no-plugins` if you want to always use the latest stable version of Kestra and use only your custom plugins.

If your deployment startegy is to pin the version, make sure to change the image to:
- `kestra/kestra:v0.18.0` if you want to have all plugins included in the image
- `kestra/kestra:v0.18.0-no-plugins` if you prefer to use only your custom plugins.

If you are using the `develop` images that include most recently developed (but not yet released) features and bug fixes, make sure to change the image to: 
- `kestra/kestra:develop` if you want to have all plugins included in the image
- `kestra/kestra:develop-no-plugins` if you prefer use have only your custom plugins.

We believe that this change will make your deployments easier and will make it clear which image to use. If you have any questions or need help with this change, please reach out to us on our [community Slack](https://kestra.io/slack).

### New mechanism of the Purge tasks (non-breaking)

We've [changed](https://github.com/kestra-io/kestra/pull/4298) **the mechanism of the Purge tasks** to make it more performant and reliable:
- `io.kestra.plugin.core.storage.Purge` has been renamed to `io.kestra.plugin.core.execution.PurgeExecutions` to reflect that it only purges data related to executions (e.g. not including trigger logs, to purge those you should use the `PurgeLogs` task) — we've added an alias so that using the old task type will still work but it will emit a warning. We recommend using the new task type.
- `io.kestra.plugin.core.storage.PurgeExecution` has been renamed to `io.kestra.plugin.core.storage.PurgeCurrentExecutionFiles` — we've added an alias so that using the old task type will still work but it will emit a warning. Also here, we recommend adjusting your flow code to match the new task type.

Overall, starting with the 0.18.0 release, the recommended way to clean execution and logs is using a combination of `io.kestra.plugin.core.execution.PurgeExecutions` but without logs and the newly added `io.kestra.plugin.core.log.PurgeLogs` task that removes all logs (both Execution and Trigger logs) in a performant batch operation. Combining those two together will give you the same functionality as the old `io.kestra.plugin.core.storage.Purge` task but in a more performant and reliable way (roughly 10x faster as compared to the old task).

```yaml
id: purge
namespace: company.myteam
description: |
  This flow will remove all executions older than one month and all logs older than one month.
  We recommend running this flow daily to avoid running out of disk space and keep the purging operation efficient.

tasks:
  - id: purge_executions
    type: io.kestra.plugin.core.execution.PurgeExecutions
    endDate: "{{ now() | dateAdd(-1, 'MONTHS') }}"
    purgeLog: false
    
  - id: purge_logs
    type: io.kestra.plugin.core.log.PurgeLogs
    endDate: "{{ now() | dateAdd(-1, 'MONTHS') }}"

triggers:
  - id: daily
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "@daily"
```

### KV Store permission must be added manually for now (non-breaking)

Starting with the 0.18.0 release, we've [introduced](https://github.com/kestra-io/kestra-ee/pull/1325#issuecomment-2213749768) a new `KVSTORE` permission that allows users to access the new KV Store functionality. This permission must be added manually for now to all Roles that need access to the KV Store.

If you have any users and Groups that want to leverage the new KV Store functionality, make sure to update their RBAC to include the new `KVSTORE` permission.
