### ISSUE TITLE
Add SQL Server backend to EE Architecture and EE configuration

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1618]
### Description

Microsoft SQLServer will be part of 0.18 as a preview feature. 

We should add the relevant Configuration + extend our Architecture pages to include it.

**Comment by loicmathieu** [comment]
Configuration used to test the feature:
```
kestra:
  repository:
    type: sqlserver
  queue:
    type: sqlserver

datasources:
  sqlserver:
    url: jdbc:sqlserver://localhost:1433
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: P4ssw0rd
    dialect: SQL_SERVER
# Uncomment only if your database is not encrypted
#    data-source-properties:
#      encrypt: false
```
