### ISSUE TITLE
Editions and Version Label doesn't appear in docs

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/docs#1622]
### Describe the issue

The `release` tag is not showing up anymore.
```yaml
---
title: Plugin Discovery Mechanism
icon: /docs/icons/migration-guide.svg
release: 0.17.0
---
```
![Screenshot 2024-08-05 at 17 07 21](https://github.com/user-attachments/assets/9debfd8e-f9ec-4376-9b96-604de100f0eb)

Same for the `editions` tag
```yaml
---
title: Setup
icon: /docs/icons/admin.svg
editions: ["EE"]
---
```
![Screenshot 2024-08-05 at 17 08 19](https://github.com/user-attachments/assets/2f67b61f-4342-43cc-b998-35645bb3a0a0)

(You can see where it wants to display it, but it's blank.

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
