### ISSUE TITLE
Implement a new layout for the How-To Guide on the Website (Docs section)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1694]
### Description

Figma design https://www.figma.com/design/g8Di3M1gbajOjOqp0ZrzXO/02_Kestra.io?node-id=12960-13588&t=qT4Km1eGWoRd9MLL-1 

![image](https://github.com/user-attachments/assets/7fa9afb8-2483-4174-90ce-cd6ae2d42e81)

The frontmatter fields that we'll need for the Filters are: 
- `stage` — a single string that can be one of "Getting Started", "Intermediate" and "Advanced" 
- `topics` — an array accepting multiple string values 

![image](https://github.com/user-attachments/assets/4f5727aa-d7ca-4940-8ae5-0c4203c3b1d3)

Example frontmatter:
```yaml
---
title: Custom Scripts
icon: /docs/icons/plugins.svg
stage: Getting Started 
version: ">= 0.18.0"
editions: ["OSS", "EE"]
topics:
  - DevOps
  - Python 
---
```
