### ISSUE TITLE
QA and document Linear, Zendesk and Hubspot plugins to create issues/tickets

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1727]
### Description

There are 3 plugins which are not fully QAed - they are missing Icon (likely title is also wrong -- see the image below)
- [x]  https://develop.kestra.io/plugins/plugin-linear/tasks/issues/io.kestra.plugin.linear.issues.create Linear
- [x]  https://develop.kestra.io/plugins/plugin-hubspot/tasks/tickets/io.kestra.plugin.hubspot.tickets.create Hubspot
- [x]  https://develop.kestra.io/plugins/plugin-zendesk/tasks/tickets/io.kestra.plugin.zendesk.tickets.create Zendesk

For each of those, we should:
- fix the plugin icon + title to ensure the docs are displayed correctly (see image)
- fully validate that the plugin is working as expected 
- add full plugin examples -- atm, all those examples show only single task example
- add a System blueprint that will open an issue/ticket anytime some execution in a company's root namespace fails -- see example below:

```yaml
id: create_ticket_on_failure
namespace: system

tasks:
- id: linear
  type: io.kestra.plugin.linear.issues.Create
  token: your_api_token
  team: MyTeamName
  title: Workflow failed
  description: "{{ execution.id }} has failed on {{ taskrun.startDate }}. See the link below for more details"
  labels:
    - Bug
    - Workflow
        
triggers:
  - id: on_failure
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionStatusCondition
        in:
          - FAILED
          - WARNING
      - type: io.kestra.plugin.core.condition.ExecutionNamespaceCondition
        namespace: company
        comparison: PREFIX
```

![image](https://github.com/user-attachments/assets/d05a5fca-9e47-4f37-81c1-4dac12dfe659)
