### ISSUE TITLE
Bad String with % in executions/trigger

### ISSUE THREAD

**Issue by DimonGit** [kestra-io/docs#2012]
### Describe the issue

Hi, 
kestra 0.20.0
try call api /api/v1/executions/trigger/{namespace}/{id} 
with headers
"content-type": "multipart/form-data",
"accept": "application/json, text/plain, */*",

in multipart init one string variable 
example:
var="some%thing"
I finally get an answer
500 {"message":"Internal server error: Bad string: '--c6c68c88f09e4ea7b9dfd53938bd6292\r\nContent-Type: application/json\r\nContent-Length: 21\r\n\r\n{\"var\": \"some%thing\"}\r\n--c6c68c88f09e4ea7b9dfd53938bd6292--\r\n'","logref":null,"path":null,"_links":{"self":{"href":"/api/v1/executions/trigger/{namespace}/{id} ","templated":false,"profile":null,"deprecation":null,"title":null,"hreflang":null,"type":null,"name":null}},"_embedded":{}}

reason in char %

### Environment

- Kestra Version: 0.20.0
- Operating System (OS/Docker/Kubernetes): Kubernetes
- Java Version (if you don't run kestra in Docker):

**Comment by Ben8t** [comment]
Hello, can you share a full flow and reproducer please ?

**Comment by Ben8t** [comment]
Hello, @DimonGit , can you send your full flow please? Not sure ot have understand where is the `var="some%thing"` 🤔

**Comment by DimonGit** [comment]
```python
import asyncio
from aiohttp import (
    ClientSession, BasicAuth
)
import aiohttp

# kestra ver 0.20.7
BASE_URL = "base url to kestra"


async def test_kestra_call(url: str):
    headers: dict[str, str] = {
        "content-type": "multipart/form-data",
        "accept": "application/json, text/plain, */*",
    }

    auth_conf = BasicAuth(
        'kestra',
        'kestra',
    )
    with aiohttp.MultipartWriter('mixed') as mpwriter:
        mpwriter.append_json(
            {"var": "some%thing"},  # ??? boom 500 {"message":"Internal server error: Bad string: '--e952f337c81f471fbe227c5fc647a36b\r\nContent-Type: application/json\r\nContent-Length: 21\r\n\r\n{\"var\": \"some%thing\"}\r\n--e952f337c81f471fbe227c5fc647a36b--\r\n'","logref":null,"path":null,"_links":{"self":{"href":"/api/v1/executions/trigger/tutorial/hello-world","templated":false,"profile":null,"deprecation":null,"title":null,"hreflang":null,"type":null,"name":null}},"_embedded":{}}
            #{"var": "something"},  # ok 200
        )
        async with ClientSession(base_url=BASE_URL, headers=headers,
                                 auth=auth_conf, ) as client:
            async with client.post(url, ssl=False, data=mpwriter) as resp:
                res = await resp.text()
                return res, resp.status


if __name__ == '__main__':
    r, s = asyncio.run(
        test_kestra_call(
            "/api/v1/executions/trigger/tutorial/hello-world")
    )
    print(s, r)
```

**Comment by DimonGit** [comment]
```yaml
id: hello-world
namespace: tutorial
description: Hello World

inputs:
  - id: user
    type: STRING
    defaults: Rick Astley

tasks:
  - id: first_task
    type: io.kestra.plugin.core.debug.Return
    format: thrilled

  - id: second_task
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - sleep 0.42
      - echo '::{"outputs":{"returned_data":"mydata"}}::'

  - id: hello_world
    type: io.kestra.plugin.core.log.Log
    message: |
      Welcome to Kestra, {{ inputs.user }}! 
      We are {{ outputs.first_task.value}} to have You here!

triggers:
  - id: daily
    type: io.kestra.plugin.core.trigger.Schedule
    disabled: true
    cron: 0 9 * * *
```
