### ISSUE TITLE
Add best practices docs page for handling flow outputs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#2024]
### Description

Example use case: user wants that a flow outputs either the output of task 1 or the output of task 2 conditionally e.g. take task2 output if task1's output is null

Example flow demonstrating conditionally returning some outputs (for docs, replace those inputs with actual tasks returning something):

```yaml
id: myflow
namespace: company.team

inputs:
  - id: first
    type: STRING
    required: false
  - id: second
    type: STRING
    defaults: myvalue

tasks:
  - id: final_output
    type: io.kestra.plugin.core.debug.Return
    format: "{{ inputs.first ?? inputs.second }}"

outputs:
  - id: final_flow_output
    type: STRING
    value: "{{ outputs.final_output }}"
```
