### ISSUE TITLE
Add How to Guide showing how to fetch data from external sources in inputs dropdowns

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#2129]
### Description

Some users want to fetch dropdown values (fields end user should select when launching an execution) from external source. We don't support that directly, but we support fetching that from KV Store. This means user needs to have a scheduled flow that will regularly populate/update the KV pair based on that external data and then reference that KV pair in the flow that needs dynamic dropdown input values.

The how to guide should walk user how to create those 2 flows:
1. one flow that will regularly populate the values for KV Store (e.g. daily/hourly, depending on how frequently that data changes) + storing those in KV Store
2. a flow used by app referencing those in SELECT/MULTISELECT field

First:

```yaml
id: add_kv_pairs
namespace: company.team

tasks:
# add a task fetching that data from external source, then pass output here under value property
  - id: access_permissions
    type: io.kestra.plugin.core.kv.Set
    key: "{{ task.id }}"
    kvType: JSON
    value: "{{ outputs.fetch.data }}"

# add schedule trigger
```

Flow that references that KV pair:
```yaml
reference that kv in the input:
id: request_resources
namespace: company.team

inputs:
  - id: access_permissions
    displayName: Access Permissions
    type: SELECT
    expression: "{{ kv('access_permissions') }}"
```
