### ISSUE TITLE
Azure AKS UI should be simplified

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/docs#2242]
### Describe what's missing in our docs

In [this section](https://kestra.io/docs/installation/kubernetes-azure-aks#access-kestra-ui) we tell the end user that they must deploy an Azure Application Gateway in order to configure access to the UI. 

This is not user-friendly as the configuration for an Application Gateway is quite complex. I would propose dropping this as for users coming to Kestra on AKS for the first time it would be easier to suggest deploying either a load balancer directly on the cluster or to just port-forward. 

E.g. load balancer
```
# Create the file
cat << EOF >> loadbalancer.yaml
apiVersion: v1
kind: Service
metadata:
  name: kestra-webserver
spec:
  selector:
    app.kubernetes.io/component: webserver
  ports:
    - protocol: TCP
      port: 80        # This is the port exposed by the service (you can change it if needed)
      targetPort: 8080 # This is the port your web server is listening on inside the pod
  type: LoadBalancer  # This exposes the service externally via a cloud LoadBalancer
EOF

# create the service
kubectl apply -f loadbalancer.yaml
```

**Comment by tchiotludo** [comment]
snippet of values that was working in the past with EKS: 

Need to validate if it's still relevant 
```
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      alb.ingress.kubernetes.io/healthcheck-path: /ping
```
