### ISSUE TITLE
Add docs section explaining the difference between finally + errors + afterExecution 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#2350]
### Describe what's missing in our docs

Add docs section explaining the difference between finally (cleanup tasks), errors (failure alert) and afterExecution (custom alerts on any state)

Would be great to add the new property + an example here https://github.com/kestra-io/kestra/blob/develop/ui/src/assets/docs/basic.md

**Comment by aj-emerich** [comment]
For reference: https://github.com/kestra-io/kestra-ee/issues/2792

**Comment by aj-emerich** [comment]
```yaml
id: state_demo
namespace: company.team

tasks:
  - id: run
    type: io.kestra.plugin.core.log.Log
    message: Execution {{ execution.state }} # Execution RUNNING
  
  - id: fail
    type: io.kestra.plugin.core.execution.Fail

finally:
  - id: log 
    type: io.kestra.plugin.core.log.Log
    message: Execution {{ execution.state }} # Execution RUNNING

afterExecution:
  - id: log 
    type: io.kestra.plugin.core.log.Log
    message: Execution {{ execution.state }} # Execution FAILED
```
