### ISSUE TITLE
Document how to trigger backfills via an API call on both OSS and EE

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#2500]
### Describe what's missing in our docs

Steps to reproduce below -- @aj-emerich you can use it as a basis for the doc (worth starting with OSS and then add a section explaining this setup in EE with a service account):

---

First, I created a new tenant called `release`. (doesn't need to be included in the doc)

Then, I created a flow file locally, e.g.:

```bash
cat >> flow.yaml
```

paste:

```yaml
id: scheduled_flow
namespace: dev
tasks:
  - id: label
    type: io.kestra.plugin.core.execution.Labels
    labels:
      scheduledDate: "{{trigger.date ?? execution.startDate}}"
  - id: external_system_export
    type: io.kestra.plugin.scripts.shell.Commands
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    commands:
      - echo "processing data for {{trigger.date ?? execution.startDate}}"
      - sleep $((RANDOM % 5 + 1))
triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/30 * * * *"
```

control C. 

## API token

Create an API token (ideally for a Service Account rather than a User Account) and attach an Admin role. Then create an API token and export it:

```bash
export KESTRA_API_TOKEN="VXLBGO***"
```

Add the flow via curl to test if the API token is working:

```bash
curl -X POST http://localhost:8080/api/v1/release/flows \
  -H "Authorization: Bearer $KESTRA_API_TOKEN" \
  -H "Content-Type: application/x-yaml" \
  --data-binary @flow.yaml
```

You should see the flow in your tenant. 

Now triggering a backfill using my tenant ID called `release`

```bash
curl -X PUT http://localhost:8080/api/v1/release/triggers \
  -H "Authorization: Bearer $KESTRA_API_TOKEN" \
  -H "X-Kestra-Tenant: release" \
  -H "Content-Type: application/json" \
  -d '{
    "namespace": "dev",
    "flowId":    "scheduled_flow",
    "triggerId": "schedule",
    "tenantId": "release",
    "backfill":  {
      "start": "2025-04-29T11:30:00Z",
      "end":   null
    }
  }'
```

Response:

```bash
{"tenantId":"release","namespace":"dev","flowId":"scheduled_flow","triggerId":"schedule","date":"2025-04-29T16:43:25Z","nextExecutionDate":"2025-04-29T12:00:00Z","backfill":{"start":"2025-04-29T11:30:00Z","end":"2025-04-29T16:45:44.842161691Z","currentDate":"2025-04-29T11:30:00Z","paused":false,"previousNextExecutionDate":"2025-04-29T17:00:00Z"},"disabled":false}
```
