### ISSUE TITLE
Revisit the Caching docs page

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#2639]
### Describe what's missing in our docs

This page [Caching](https://kestra.io/docs/concepts/caching) could be revisited to have more example, @aj-emerich perhaps integrate the new dependencies property added in 0.23 into the same page? (non-urgent, sth for later after the release)

Useful example with installing deps into a `--cache-dir`:
 
```yaml
id: cache
namespace: company
tasks:
  - id: fs
    type: io.kestra.plugin.core.flow.WorkingDirectory
    cache:
      patterns:
        - cache/pip/**
      ttl: PT24H

    tasks:
      - id: python_script
        type: io.kestra.plugin.scripts.python.Script
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
        beforeCommands:
          - pip install --cache-dir cache/pip pandas
        script: |
          import pandas as pd
          print(pd.__version__)
```

worth adding some screenshots or Arcade to show that caching works:

![Image](https://github.com/user-attachments/assets/520ffd64-26f7-4440-a4b9-c714fcc84992)

![Image](https://github.com/user-attachments/assets/7c9b6a60-9c87-4ca7-9d1d-4c60e3b1a043)
