### ISSUE TITLE
Add docs on how to set custom dependencies (e.g. for`DbtCLI` task) and how to cache them

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#475]
### Feature description

Examples:

```yaml
id: dbtGitDockerDuckDB
namespace: blueprint

tasks:
  - id: dbt
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
    - id: cloneRepository
      type: io.kestra.plugin.git.Clone
      url: https://github.com/kestra-io/dbt-demo
      branch: main

    - id: dbt-build
      type: io.kestra.plugin.dbt.cli.DbtCLI
      runner: DOCKER
      docker:
        image: python:3.11-slim
      beforeCommands:
        - pip install dbt-bigquery==1.5.0
      profiles: |
        ...
      commands:
        - dbt deps
        - dbt build
```

Add example installing these into venv and caching venv folder:

```yaml
  - id: working_dir
    type: io.kestra.core.tasks.flows.WorkingDirectory
    cache:
      patterns:
        - venv/**
      ttl: PT30D
```
