### ISSUE TITLE
Add structured tutorials section

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#911]
### Feature description

Together with @Ben8t we discussed a possibility to add a docs section structured by skill level and topic.

Proposal: [kestra.io/docs/tutorials](http://kestra.io/docs/tutorials)

Front matter:
```yaml
---
title: Flow
icon: /docs/icons/components.svg
level: Beginner # Intermediate, Advanced
topic: BigQuery # comma separated tags
---
```

may look similarly to:
![image](https://github.com/kestra-io/docs/assets/86264395/d59e366f-1299-4039-8ce2-8a0173d88a2f)

It can have a tag `Best practices` to share best practices

Best if it's managed via docs code so it's easier to link to other docs.

@Nico-Kestra maybe you have an idea for a design of such page?
