### ISSUE TITLE
docs > developer-guide > cicd > deploy-flows-from-a-flow - references to bash, replace with shell.Commands

### ISSUE THREAD

**Issue by kriko** [kestra-io/docs#916]
### Issue description

Under [docs > developer-guide > cicd > **deploy-flows-from-a-flow**](https://kestra.io/docs/developer-guide/cicd#deploy-flows-from-a-flow) the current example is the following:

```
id: ci-cd
namespace: prod
tasks:
  - id: github-ci-cd
    type: io.kestra.core.tasks.flows.Worker
    tasks:
      - id: clone-repository
        type: io.kestra.plugin.git.Clone
        url: https://github.com/anna-geller/kestra-ci-cd
        branch: main
      - id: validate-flows
        type: io.kestra.core.tasks.scripts.Bash
        commands:
          - /app/kestra flow validate flows/
      - id: deploy-flows
        type: io.kestra.core.tasks.scripts.Bash
        commands:
          - /app/kestra flow namespace update prod flows/prod/
          - /app/kestra flow namespace update prod.marketing flows/prod.marketing/
triggers:
  - id: github
    type: io.kestra.core.models.triggers.types.Webhook
    key: "yourSecretKey1234"
```

However, since [io.kestra.core.tasks.scripts.Bash](https://kestra.io/plugins/plugin-script-shell/tasks/io.kestra.core.tasks.scripts.bash) is deprecated and in my use case - I recently developed problems using this deprecated task, but I managed to solve the problems by substituting for shell.Commands, however, the change might not be that straight forward, so I'll provide the correct flow.

```
id: ci-cd
namespace: prod
tasks:
  - id: github-ci-cd
    type: io.kestra.core.tasks.flows.Worker
    tasks:
      - id: clone-repository
        type: io.kestra.plugin.git.Clone
        url: https://github.com/anna-geller/kestra-ci-cd
        branch: main

      - id: validate-flows
        type: io.kestra.plugin.scripts.shell.Commands
        description: "Validate flows from Git before deploying them."
        runner: PROCESS
        warningOnStdErr: false
        commands:
          - /app/kestra flow validate flows/

      - id: deploy-flows
        type: io.kestra.plugin.scripts.shell.Commands
        description: "Deply flows to the Kestra namespace."
        runner: PROCESS
        warningOnStdErr: false
        commands:
          - /app/kestra flow namespace update prod flows/prod/
          - /app/kestra flow namespace update prod.marketing flows/prod.marketing/

triggers:
  - id: github
    type: io.kestra.core.models.triggers.types.Webhook
    key: "yourSecretKey1234"
```

It is important to point out that accessing the current Kestra instance requires the PROCESS runner. Even though it might be theoretically possible to use a Docker container runner, specifying the Kestra image, I was unable to do so because the container had no access to Kestra through the internal network. PROCESS runner is the closest conversion from the bash task.
