### ISSUE TITLE
Add ForEachItem example in the EachSequential/EachParallel tasks

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#983]
### Feature description

![image](https://github.com/kestra-io/docs/assets/86264395/aa5516f6-b0e7-4893-ba17-18d93a3fbd9c)

```yaml
tasks:
  - id: loop_cdc_tables
    type: io.kestra.core.tasks.flows.EachSequential
    value: "{{ trigger.uris | keys }}"
    tasks:
      - id: trigger_sub_flow_for_cdc_events
        type: io.kestra.core.tasks.flows.ForEachItem
        items: "{{ trigger.uris[parent.taskrun.value] }}" 
        batch:
          rows: 1000
        flowId: process_events
        wait: true
        transmitFailed: true
        inputs:
          data: "{{ taskrun.items }}"

triggers:
  - id: trigger
    type: io.kestra.plugin.debezium.mysql.Trigger
    hostname: host
    password: "pwd"
    username: username
    port: "3306"
    maxKeys: 1
    ignoreDdl: true
    format: INLINE
    snapshotMode: INITIAL
    includedTables:
      - boot_staging.statuses
      - boot_staging.hosts
```
